ALTER TABLE account ALTER COLUMN update_at DROP NOT NULL;
ALTER TABLE account ALTER COLUMN deleted_at DROP NOT NULL;

ALTER TABLE book ALTER COLUMN update_at DROP NOT NULL;
ALTER TABLE book ALTER COLUMN deleted_at DROP NOT NULL;

