ALTER TABLE account ALTER COLUMN update_at SET NOT NULL;
ALTER TABLE account ALTER COLUMN deleted_at SET NOT NULL;

ALTER TABLE book ALTER COLUMN update_at SET NOT NULL;
ALTER TABLE book ALTER COLUMN deleted_at SET NOT NULL;
